### ISSUE TITLE
[Suggestion]: Automatic Force Infuser (redstone or other)

### ISSUE THREAD

**Issue by Ranzuu** [Mrbysco/ForceCraft#91] opened 2024-07-10 17:38 UTC
### General Info

- [X] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

The idea is to add a thing into the force infuser to automatically infuse. 
If items inside match, you provide the redstone signal to the force infuser to autocraft the given item. Like redstone pulse will infuse one item.

**Comment by Mrbysco** [comment] 2024-07-11 10:37
Duplicate of #89
Being able to infuse by supplying a Redstone signal is already a thing in ForceCraft for 1.20.4

**Closed as completed** 2024-07-11 10:37 UTC
Labels: enhancement

**Comment by Ranzuu** [comment] 2024-07-11 14:37
Ah didn't know. I'm at 1.20.1. Well very nice to hear that, thank you :>
