### ISSUE TITLE
[Suggestion]: Automation

### ISSUE THREAD

**Issue by CookieKiller01** [Mrbysco/ForceCraft#95] opened 2024-08-06 20:09 UTC
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

it would be nice if we could automate the force infuser

**Comment by Mrbysco** [comment] 2024-08-06 20:59
Already possible in 1.20.4
Duplicate of https://github.com/Mrbysco/ForceCraft/issues/89

**Closed as completed by Mrbysco** 2024-08-06 20:59 UTC
Labels: enhancement
