### ISSUE TITLE
[Bug]: Upgrade Core is uncraftable

### ISSUE THREAD

**Issue by ninjabunny66** [Mrbysco/ForceCraft#68] opened 2022-12-19 23:00 UTC
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.19.2-forge-43.1.57

### Minecraft version

1.19.2

### Mod version

3.2.0

### Java version

Version 8 Update 333

### Issue Description

Modpack: FTB Presents Direwolf20 1.19 Version 1.0.1

Note: 
Multiplayer testing occurred on a LAN server, not a true server.
 
Issue:
Crafting a Force Rod with an Experience Tome holding experience exceeding the stated requirement of 100 points does not allow for crafting an Upgrade Core despite the recipe appearing in both JEI and Force and You as such.

Expected Result:
Upgrade Core can be crafted.

Steps to Reproduce:
1. Enter a world with operator permissions
2. Use the command "/xp add @p 1000 points"
3. Use the command "/give @p forcecraft:force_rod"
4. Use the command "/give @p forcecraft:experience_tome"
5. Right click the tome to absorb all 1000 xp points
6. Place the rod and tome within a crafting grid (inventory and vanilla crafting table were tested), the Upgrade Core does not appear within the output of the crafting grid.

### Additional Information

JEI with recipe:
<img width="481" alt="image" src="https://user-images.githubusercontent.com/71219645/208542989-7ef00bc0-1056-4e20-82af-8f2de634c16c.png">

In actual crafting grid:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/71219645/208543628-d87b4196-5d34-4b5c-af6e-9329af00600a.png">

**Comment by Mrbysco** [comment] 2022-12-19 23:31
Can't reproduce your issue 
![image](https://user-images.githubusercontent.com/9308260/208548110-f4f4f869-d8a6-4b40-bc6c-4bec4902a196.png)

**Comment by Mrbysco** [comment] 2022-12-19 23:32
Are you sure you actually have experience in the tome? It needs a minimum of 100 which you can see by holding shift while hovering over the tome

**Comment by ninjabunny66** [comment] 2022-12-19 23:37
<img width="390" alt="image" src="https://user-images.githubusercontent.com/71219645/208548648-9dcda06a-c65c-4504-8ac7-0400959098ca.png">

**Comment by Mrbysco** [comment] 2022-12-19 23:39
![image](https://user-images.githubusercontent.com/9308260/208548753-d41a4e64-b180-4d4c-ab30-6c17b4ed284c.png)
![image](https://user-images.githubusercontent.com/9308260/208548791-9c93caba-99bd-46ee-84af-d03e3645aad4.png)
![image](https://user-images.githubusercontent.com/9308260/208548822-01e8bb75-9ecc-442d-90a3-e9e18592aa15.png)

**Comment by Mrbysco** [comment] 2023-01-01 17:54
I'm unable to reproduce the issue

**Comment by Saereth** [comment] 2023-01-14 00:18
@Mrbysco this is still an issue in the latest version (1.4.0) of direwolf20 1.19, I'm not doing anything with the recipes
![image](https://user-images.githubusercontent.com/9200909/212440519-88fc787f-c45b-4962-b685-4a24696e19dc.png)

![image](https://user-images.githubusercontent.com/9200909/212440550-f4a788d7-1694-4d8e-898f-e6e475be6b81.png)

**Comment by Mrbysco** [comment] 2023-01-14 00:21
I'm unable to reproduce the issue

**Comment by Saereth** [comment] 2023-01-14 02:35
doesn't occur in a barebones 1.19 instance it seems sooo... binary removal time -_- I'll let you know when I find the culprit in case this comes up again in the future.

**Comment by KaldurRahm** [comment] 2023-01-29 18:38
I believe the issue is with the crafting table mod that renders the crafting tables contents above it. This bug is even documented in Direwolf20's videos. When I take that mod out of the DW20 pack Forcecraft works as intended.

**Comment by Woodka7** [comment] 2023-02-20 01:34
Nope Still not fixed still receiving this bug while playing DIrewolf20 1.19.2 1.3.2

**Comment by Mrbysco** [comment] 2023-02-20 13:08
Still unable to reproduce

**Comment by Saereth** [comment] 2023-02-20 13:10
I can't reproduce it either in dw 1.3.2 nor have or other testers either
way you can close this ticket as the original issue was never at your mods
fault anyway

**Closed** 2023-02-20 13:24 UTC
Labels: bug, question

**Comment by schindlershadow** [comment] 2024-10-02 23:24
this bug is back in 6.0.4
![Screenshot from 2024-10-02 19-21-09](https://github.com/user-attachments/assets/a6d18fdd-3cbd-4065-a305-3d395d99d998)
tome has 100 exp in it

also another bug, when placing the tome in the crafting table, it bugs out and changes the stored exp to 100.
this happens no matter the exp stored in the tome, I tested 0, 400 and 1k

opened  #104
